// Generated by : Getx
// Command : get generate model with json/category.json

class Category {
  String? id;
  String? name;
  String? emoji;

  static const TABLE_NAME = "category";

  Category({this.id, this.name, this.emoji});

  Category.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    emoji = json['emoji'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['emoji'] = emoji;
    return data;
  }
}
