// Generated by : Getx
// Command : get generate model with json/transaction_record.json

class TransactionRecordModel {
  String? id;
  double? amount;
  String? note;
  String? category;
  String? dateTime;

  static const TABLE_NAME = "transaction_record";

  TransactionRecordModel(
      {this.id, this.amount, this.note, this.category, this.dateTime});

  TransactionRecordModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    amount = json['amount'];
    note = json['note'];
    category = json['category'];
    dateTime = json['date_time'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['amount'] = amount;
    data['note'] = note;
    data['category'] = category;
    data['date_time'] = dateTime;
    return data;
  }
}
