name: Perform CI/CD
on:
  push:
    branches: [main]

jobs:
  continuous_deployment_web:
    name: Continuous Deployment WEB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creating Gsheet Key File
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GSHEET }}
          dir: "assets/"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Deploying to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MTRACKER_394207 }}"
          channelId: live
          projectId: mtracker-394207
  
  continuous_deployment_ios:
    name: Continuous Deployment IOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creating Gsheet Key File
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GSHEET }}
          dir: "assets/"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get
      
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: POD Updated
        run: pod repo update
        working-directory: ios

      - name: Build IOS App
        run: flutter build ios --release
      
      - name: Generating IPA File
        run: mkdir Payload; mv Runner.app/ Payload; zip -qq -r -9 Payload.ipa Payload
        working-directory: build/ios/Release-iphoneos
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/Release-iphoneos/Payload.ipa
          tag: v1.0
          overwrite: true

  web_notification_success:
    if: success()
    needs: [continuous_deployment_web]
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Web Continuous Deployment Completed Successfully!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      
      - name: Send Release Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            https://mtracker-394207.web.app/

  web_notification_failure:
    if: failure()
    needs: [continuous_deployment_web]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Web Continuous Deployment Failed!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  
  ios_notification_success:
    if: success()
    needs: [continuous_deployment_ios]
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            iOS Continuous Deployment Completed Successfully!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      
      - name: Send Release Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            https://mtracker-394207.web.app/apps
      
  ios_notification_failure:
    if: failure()
    needs: [continuous_deployment_ios]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            iOS Continuous Deployment Failed!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}    

