name: Perform CI/CD
on:
  push:
    branches: [main]

jobs:
  continuous_deployment_web:
    name: Continuous Deployment WEB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creating Gsheet Key File
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GSHEET }}
          dir: "assets/"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.2"
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Deploying to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MTRACKER_394207 }}"
          channelId: live
          projectId: mtracker-394207
  
  continuous_deployment_ios:
    name: Continuous Deployment IOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creating Gsheet Key File
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GSHEET }}
          dir: "assets/"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.2"
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get

      - name: POD Updated
        run: pod repo update
        working-directory: ios

      - name: Build IOS App
        run: flutter build ios --release --no-codesign
      
      - name: Generating IPA File
        run: mkdir Payload; mv Runner.app/ Payload; zip -qq -r -9 Payload.ipa Payload
        working-directory: build/ios/Release-iphoneos
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/Release-iphoneos/Payload.ipa
          tag: v1.0
          overwrite: true

  web_notification_success:
    if: success()
    needs: [continuous_deployment_web]
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Web Continuous Deployment Completed Successfully!!!

            Web Release : [MTracker](https://mtracker-394207.web.app/)

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  
  web_notification_failure:
    if: failure()
    needs: [continuous_deployment_web]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Web Continuous Deployment Failed!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  
  ios_notification_success:
    if: success()
    needs: [continuous_deployment_ios]
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            iOS Continuous Deployment Completed Successfully!!!

            iOS Release : [MTracker](itms-services://?action=download-manifest&url=https://raw.githubusercontent.com/Saleh7/ipa-install/master/testapp.plist)

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  
  ios_notification_failure:
    if: failure()
    needs: [continuous_deployment_ios]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            iOS Continuous Deployment Failed!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}    

