name: Perform CI/CD
on:
  push:
    branches: [main]

jobs:
  continuous_deployment_web:
    name: Continuous Deployment WEB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creating Gsheet Key File
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GSHEET }}
          dir: "assets/"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Deploying to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MTRACKER_394207 }}"
          channelId: live
          projectId: mtracker-394207

  web_notification_success:
    if: success()
    needs: [continuous_deployment_web]
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Web Continuous Deployment Completed Successfully!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      
      - name: Send Release Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            https://mtracker-394207.web.app/

  web_notification_failure:
    if: failure()
    needs: [continuous_deployment_web]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Web Continuous Deployment Failed!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}