name: Perform CI/CD
on:
  push:
    branches: [main]

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.2"
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get

      - name: Check Code Format
        run: dart format . --set-exit-if-changed

      - name: Analyze Code
        run: dart analyze .

      - name: Send Success Telegram Message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Continuous Integration Completed Successfully!!!

            User: ${{ github.actor }}

            Commit message: ${{ github.event.commits.message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: Send Failure Telegram Message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Continuous Integration Failed!!!

            User: ${{ github.actor }}

            Commit message: ${{ github.event.commits.message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  continuous_deployment:
    name: Continuous Deployment
    needs: continuous_integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creating Gsheet Key File
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GSHEET }}
          dir: "assets/"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.2"
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Deploying to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MTRACKER_394207 }}"
          channelId: live
          projectId: mtracker-394207

      - name: Send Success Telegram Message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Continuous Deployment Completed Successfully!!!

            URL: https://mtracker-394207.web.app/

            User: ${{ github.actor }}

            Commit message: ${{ github.event.commits.message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: Send Failure Telegram Message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Continuous Deployment Failed!!!

            URL: https://mtracker-394207.web.app/

            User: ${{ github.actor }}

            Commit message: ${{ github.event.commits.message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
